### ISSUE TITLE
Bootstrap import breaking theme styles

### ISSUE THREAD

**Issue by nzambello** [RedTurtle/redturtle.ads#4]
In `static/css/` there are two CSS files with an import of bootstrap.
These rules are breaking site's theme ones.

I suggest to remove those, leaving styles to themes' responsability.
I have styles for this product in a theme and I can import those without bootstrap stuffs, but IMHO styles and content types should be separated.

Another option is to add another add-on with sort of a default theme for this.

**Comment by pnicolli** [comment]
Another option could be to have an opt-out solution for styles, like a separated bundle that can be disabled if not needed.
